[package]
name = "tic-tac-toe"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
linera-sdk = "0.15.8"
serde = { version = "1.0", features = ["derive"] }

[lib]
crate-type = ["cdylib", "rlib"]
